server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mupezzuol/spring-microservice-config-server-repo
          search-paths:
          - fornecedor
          - loja
            
