server:
  port: 8888

spring:
  application:
    name: 'config-server'
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mupezzuol/spring-microservice-config-server-repo
          search-paths:
          - fornecedor
          - loja
          - transportador
  boot:
    admin:
      client:
        url:
        - http://localhost:8082

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
  endpoint:
    health:
      show-details: always